DROP TABLE IF EXISTS `ANSWERS`;
CREATE TABLE IF NOT EXISTS ANSWERS (
	a_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	q_id INT,
	answer TEXT,
	answered_by VARCHAR(50),
	created_at DATETIME,
    key `q_id` (`q_id`)
);
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (1, 1, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Shep Maywood', '2020-09-23 14:57:37');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (2, 2, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'Pearle Hulstrom', '2020-07-15 20:12:23');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (3, 20, 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.', 'Guenevere Laville', '2020-02-11 18:09:32');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (4, 14, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'Alane O''Caherny', '2020-04-30 09:43:04');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (5, 12, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 'Nerty Gidman', '2020-05-17 17:49:58');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (6, 6, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Hal Sumner', '2020-11-19 12:18:52');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (7, 15, 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Gus Brunini', '2020-10-01 07:43:11');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (8, 11, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Issie Mostyn', '2020-04-13 00:03:54');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (9, 2, 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Bettine Trowel', '2020-06-06 15:42:58');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (10, 6, 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Orella Shorthouse', '2020-06-26 03:30:39');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (11, 20, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 'Bebe Patek', '2020-06-14 05:49:47');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (12, 12, 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 'Chicky Poizer', '2020-11-12 01:53:34');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (13, 10, 'Etiam vel augue.', 'Hervey Kenningham', '2020-04-10 07:42:03');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (14, 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Conny Jiggins', '2021-01-07 17:55:06');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (15, 18, 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'Antonio Fealey', '2020-02-17 09:31:23');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (16, 2, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 'Johnette Hillin', '2020-04-10 01:25:45');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (17, 6, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Leah Waldram', '2020-10-25 12:43:15');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (18, 17, 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Myranda Scamel', '2020-01-22 00:34:16');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (19, 5, 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Marley Castaner', '2020-04-15 13:18:27');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (20, 17, 'In hac habitasse platea dictumst.', 'Constantin Stredder', '2020-09-20 01:22:06');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (21, 5, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 'Arliene Brangan', '2020-08-04 09:31:30');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (22, 15, 'Phasellus sit amet erat.', 'Feodora Corkhill', '2020-03-11 18:10:51');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (23, 18, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Arney Schermick', '2020-12-21 23:14:28');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (24, 13, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', 'Abrahan Oubridge', '2020-03-29 09:32:31');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (25, 14, 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Leese Andriulis', '2020-02-01 19:01:55');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (26, 10, 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 'Derward Duhig', '2020-05-01 23:58:08');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (27, 7, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'Latrina Gray', '2020-04-29 19:07:04');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (28, 12, 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'Ellary Elloway', '2020-10-23 05:04:51');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (29, 9, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'Alia Mandy', '2020-01-29 03:55:13');
insert into ANSWERS (a_id, q_id, answer, answered_by, created_at) values (30, 14, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'Valerye Braiden', '2021-01-06 12:11:28');
